# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170804_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Type your comment'),
        ),
    ]
